Suparna_Assignment_22_10min+5Min
KrishnaKTechnocredits/JAVATechnoJun20 pull request #641
Opened 2020-07-01 08:42 UTC by SuparnaNJune20

![PalindromeNo](https://user-images.githubusercontent.com/66842758/86223050-ad046b00-bba4-11ea-8619-58322caa3e7f.PNG)
![PalindromeString](https://user-images.githubusercontent.com/66842758/86223055-ae359800-bba4-11ea-864f-ffb974a6e1d3.PNG)

2020-07-01 11:26 UTC, VireshJJun20 commented on src/suparnaNJune20/Assignment22/PalindromeString.java
> +	void checkPalindromeStringMethod2(String str1) {
Code looks good to me.

2020-07-01 11:26 UTC, VireshJJun20 commented on src/suparnaNJune20/Assignment22/PalindromeNo.java
> +	void checkPalindromeNo(int num) {
Neat and clean code.

2020-07-01 11:29 UTC, VireshJJun20 commented on src/suparnaNJune20/Assignment22/PalindromeString.java
> +	void checkPalindromeStringMethod2(String str1) {
Another method can be simply reverse the input string and then compare it with original one.
number of coding lines will also get decreased. you can try if you want. :)

2020-07-01 11:30 UTC, VireshJJun20 requested changes
Approved

2020-07-01 11:36 UTC, VireshJJun20 approved these changes

2020-07-02 07:24 UTC, KrishnaKTechnocredits commented on src/suparnaNJune20/Assignment22/PalindromeNo.java
> +		int tempNum = 0, orignalNum = num;
The variable name should be revNumber, not tempNumber.

2020-07-02 07:25 UTC, KrishnaKTechnocredits commented on src/suparnaNJune20/Assignment22/PalindromeString.java
> +		if (lIndex / 2 != 0) {
This logic is not acceptable. Always simply the logic.

2020-07-02 07:26 UTC, merged